// デザインB（design-B-copilot.dc.html）の「全モジュール（20分類）」データ。
// go はデザイン上の画面遷移先キー。実装済み判定は /modules ページが行う。
export type ModuleItem = { l: string; go?: string };
export type ModuleGroup = { icon: string; label: string; items: ModuleItem[] };

export const MODULES: ModuleGroup[] = [
  { icon: '🔎', label: '統合検索', items: [
      { l: 'すべて検索', go: 'search' },
      { l: '特許検索', go: 'search' },
      { l: '技術検索', go: 'search' },
      { l: '論文・研究検索', go: 'search' },
      { l: 'NETIS検索', go: 'search' },
      { l: '出願人・企業検索' },
      { l: '発明者・研究者検索' },
      { l: 'IPC / CPC検索' },
      { l: 'Claim検索' },
      { l: 'AI自然言語検索', go: 'copilot' },
      { l: '類似技術検索' },
      { l: '検索履歴・保存検索' }
    ] },
  { icon: '💡', label: '技術インテリジェンス', items: [
      { l: '技術一覧' },
      { l: '工法一覧' },
      { l: '材料・製品' },
      { l: '建設機械・設備' },
      { l: 'ICT施工' },
      { l: 'BIM / CIM' },
      { l: 'AI・自動施工' },
      { l: 'ロボティクス' },
      { l: '技術比較' },
      { l: '類似技術' },
      { l: '技術評価' },
      { l: '技術関連マップ' }
    ] },
  { icon: '📜', label: '特許インテリジェンス', items: [
      { l: '特許一覧', go: 'search' },
      { l: '国内特許' },
      { l: '海外特許' },
      { l: '特許ファミリー' },
      { l: '出願人分析' },
      { l: '発明者分析' },
      { l: 'IPC / CPC分析' },
      { l: '引用・被引用' },
      { l: '権利状態' },
      { l: '審査経過' },
      { l: '類似特許' },
      { l: 'お気に入り・ウォッチ', go: 'watchs' }
    ] },
  { icon: '🔬', label: '先行技術調査', items: [
      { l: '新規調査', go: 'copilot' },
      { l: '調査案件一覧', go: 'invest' },
      { l: '先行特許' },
      { l: '先行論文' },
      { l: 'NETIS・公開技術' },
      { l: '類似技術調査' },
      { l: '構成要件別調査' },
      { l: '引用文献分析' },
      { l: '重要文献ランキング' },
      { l: '調査検索式' },
      { l: '調査履歴', go: 'invest' },
      { l: '調査レポート', go: 'report' }
    ] },
  { icon: '🧩', label: 'Claim解析', items: [
      { l: 'Claim解析' },
      { l: '独立請求項' },
      { l: '従属請求項' },
      { l: '構成要件分解' },
      { l: 'Claim Tree' },
      { l: 'Claim Chart' },
      { l: 'Claim Matrix' },
      { l: '自社技術との比較' },
      { l: '他社特許との比較' },
      { l: '複数特許比較' },
      { l: '類似度分析' },
      { l: '差分・特徴抽出' }
    ] },
  { icon: '🤖', label: 'AI特許レビュー', items: [
      { l: 'AI Patent Examiner' },
      { l: '新規性レビュー' },
      { l: '進歩性レビュー' },
      { l: '記載要件レビュー' },
      { l: '明確性レビュー' },
      { l: '先行文献比較' },
      { l: '容易想到性分析' },
      { l: '想定拒絶理由' },
      { l: '拒絶リスク評価' },
      { l: '差別化ポイント' },
      { l: '補正方向候補' },
      { l: '意見書論点候補' },
      { l: 'AIレビュー履歴' }
    ] },
  { icon: '📚', label: '論文・研究・NETIS', items: [
      { l: '論文', go: 'search' },
      { l: '学会資料' },
      { l: '研究成果' },
      { l: '大学・研究機関' },
      { l: '研究者' },
      { l: 'NETIS', go: 'search' },
      { l: '国交省技術資料' },
      { l: '公開施工事例' },
      { l: '特許との関連' },
      { l: '技術との関連' },
      { l: '最新研究トレンド' }
    ] },
  { icon: '🏗️', label: '土木技術・現場適用', items: [
      { l: '現場条件入力' },
      { l: '現場課題登録', go: 'field' },
      { l: '適用技術検索', go: 'field' },
      { l: 'Field Applicability Score', go: 'field' },
      { l: '工種適合性', go: 'field' },
      { l: '地盤・地形適合性', go: 'field' },
      { l: '気象・海象適合性', go: 'field' },
      { l: '安全性評価', go: 'field' },
      { l: '品質評価', go: 'field' },
      { l: 'CO₂・環境評価', go: 'field' },
      { l: '生産性・省人化評価', go: 'field' },
      { l: '導入難易度評価', go: 'field' },
      { l: '土木技術分類（港湾・河川・道路ほか13分類）' }
    ] },
  { icon: '🏢', label: '競合・特許ランドスケープ', items: [
      { l: '競合企業' },
      { l: '企業別出願分析' },
      { l: '技術分野比較' },
      { l: '工種別比較' },
      { l: '出願推移' },
      { l: '共同出願分析' },
      { l: '大学連携分析' },
      { l: '技術クラスタ' },
      { l: 'Patent Landscape' },
      { l: '技術マップ' },
      { l: '特許密度' },
      { l: '成長・衰退領域' },
      { l: '新興技術' },
      { l: 'ホワイトスペース' },
      { l: '自社ポジション' }
    ] },
  { icon: '🚀', label: 'R&D・発明管理', items: [
      { l: 'R&Dダッシュボード', go: 'dashboard' },
      { l: '研究テーマ' },
      { l: '技術課題' },
      { l: '技術ニーズ' },
      { l: '発明アイデア', go: 'invent' },
      { l: '発明届', go: 'invent' },
      { l: '発明者' },
      { l: 'AI発明整理' },
      { l: 'Claim候補生成' },
      { l: '先行技術調査', go: 'invest' },
      { l: '発明評価' },
      { l: 'ホワイトスペース候補' },
      { l: '改良発明候補' },
      { l: '周辺発明候補' },
      { l: '技術ロードマップ' },
      { l: '出願候補', go: 'invent' }
    ] },
  { icon: '🤝', label: 'ライセンス・知財ポートフォリオ', items: [
      { l: 'ライセンス候補' },
      { l: '開放特許' },
      { l: '技術導入候補' },
      { l: '技術供与候補' },
      { l: 'ライセンサー' },
      { l: 'ライセンシー' },
      { l: '自社開発との比較' },
      { l: 'Buy / Build / Partner' },
      { l: 'ライセンス評価' },
      { l: '自社特許一覧' },
      { l: '審査中特許' },
      { l: '登録特許' },
      { l: '失効・放棄' },
      { l: '活用状況' },
      { l: '維持優先度' }
    ] },
  { icon: '⚖️', label: '法務・知財レビュー', items: [
      { l: '法務審査依頼' },
      { l: '知財審査依頼' },
      { l: '審査案件一覧' },
      { l: 'NDA確認' },
      { l: '権利状態確認' },
      { l: '独占 / 非独占' },
      { l: '利用分野' },
      { l: '地域条件' },
      { l: '契約期間' },
      { l: 'ロイヤルティ' },
      { l: 'サブライセンス' },
      { l: '改良発明' },
      { l: '契約リスク' },
      { l: '法務確認事項' },
      { l: 'Construction-LegalOps-DX連携' }
    ] },
  { icon: '👁️', label: 'ウォッチ・モニタリング', items: [
      { l: 'マイウォッチ', go: 'watchs' },
      { l: '特許ウォッチ', go: 'watchs' },
      { l: '競合企業ウォッチ', go: 'watchs' },
      { l: '技術分野ウォッチ', go: 'watchs' },
      { l: 'IPC / CPCウォッチ' },
      { l: '発明者ウォッチ' },
      { l: '論文ウォッチ' },
      { l: 'NETISウォッチ' },
      { l: '権利状態変更', go: 'watchs' },
      { l: '新規出願', go: 'watchs' },
      { l: 'AI重要度判定', go: 'watchs' },
      { l: 'アラート一覧', go: 'watchs' },
      { l: '週次AIダイジェスト', go: 'watchs' }
    ] },
  { icon: '🧠', label: 'AIアシスタント', items: [
      { l: 'Civil IP Copilot', go: 'copilot' },
      { l: '技術調査Agent', go: 'copilot' },
      { l: 'Patent Search Agent' },
      { l: 'Research Agent' },
      { l: 'Claim Agent', go: 'copilot' },
      { l: 'Examiner Agent' },
      { l: 'Competitor Agent', go: 'copilot' },
      { l: 'Landscape Agent' },
      { l: 'Civil Engineer Agent', go: 'copilot' },
      { l: 'R&D Agent' },
      { l: 'Licensing Agent' },
      { l: 'Legal Agent' },
      { l: 'Report Agent' },
      { l: 'Agent実行履歴' },
      { l: '自律調査ジョブ', go: 'invest' }
    ] },
  { icon: '📖', label: 'ナレッジ', items: [
      { l: '技術ナレッジ' },
      { l: '特許ナレッジ' },
      { l: '論文ナレッジ' },
      { l: 'NETISナレッジ' },
      { l: '過去調査', go: 'invest' },
      { l: 'AIレビュー' },
      { l: '発明事例', go: 'invent' },
      { l: 'ライセンス事例' },
      { l: '法務レビュー結果' },
      { l: '施工事例' },
      { l: 'FAQ' },
      { l: 'RAG検索' }
    ] },
  { icon: '📊', label: 'レポート', items: [
      { l: 'レポート作成', go: 'report' },
      { l: '技術調査報告書', go: 'report' },
      { l: '特許調査報告書', go: 'report' },
      { l: '先行技術調査書', go: 'report' },
      { l: 'Claim比較レポート' },
      { l: '新規性レビュー' },
      { l: '進歩性レビュー' },
      { l: 'AI模擬審査報告' },
      { l: '競合分析', go: 'report' },
      { l: 'Patent Landscape' },
      { l: 'ホワイトスペース分析' },
      { l: '現場適用性評価', go: 'report' },
      { l: 'R&D提案' },
      { l: '経営サマリー', go: 'report' },
      { l: '出力履歴', go: 'report' }
    ] },
  { icon: '✅', label: 'ワークフロー・承認', items: [
      { l: 'マイタスク', go: 'approve' },
      { l: '承認待ち', go: 'approve' },
      { l: '技術レビュー', go: 'approve' },
      { l: '知財レビュー', go: 'approve' },
      { l: '法務レビュー', go: 'approve' },
      { l: '差戻案件' },
      { l: '承認済', go: 'approve' },
      { l: '保留' },
      { l: 'アーカイブ' },
      { l: 'コメント' },
      { l: '承認履歴', go: 'audit' }
    ] },
  { icon: '🗃️', label: 'データ管理', items: [
      { l: 'データソース' },
      { l: '特許データ' },
      { l: '論文データ' },
      { l: 'NETISデータ' },
      { l: '技術マスタ' },
      { l: 'IPC / CPCマスタ' },
      { l: '土木工種マスタ' },
      { l: '企業マスタ' },
      { l: '発明者マスタ' },
      { l: 'データクレンジング' },
      { l: '名寄せ' },
      { l: '重複管理' },
      { l: 'AI分類' },
      { l: 'データ品質' },
      { l: 'Provenance / 出典' }
    ] },
  { icon: '⚙️', label: 'システム管理', items: [
      { l: 'ユーザー管理', go: 'admin' },
      { l: 'ロール・権限', go: 'admin' },
      { l: '部門管理' },
      { l: 'プロジェクト権限' },
      { l: 'AIモデル設定' },
      { l: 'Agent設定' },
      { l: 'API設定' },
      { l: '外部データ連携' },
      { l: '通知設定' },
      { l: 'ワークフロー設定' },
      { l: 'マスタ設定' },
      { l: 'バックアップ' },
      { l: 'システム状態', go: 'admin' },
      { l: 'Feature Flags' }
    ] },
  { icon: '🛡️', label: 'セキュリティ・監査', items: [
      { l: '監査ログ', go: 'audit' },
      { l: 'ログイン履歴', go: 'audit' },
      { l: 'AI利用履歴', go: 'audit' },
      { l: '検索履歴', go: 'audit' },
      { l: 'データ閲覧履歴' },
      { l: 'Export履歴', go: 'audit' },
      { l: '更新・削除履歴' },
      { l: '承認履歴', go: 'audit' },
      { l: '権限変更履歴' },
      { l: 'セキュリティイベント', go: 'audit' },
      { l: 'データアクセス監査' }
    ] }
];